### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by jsgv** [abdala/omnipay-pagseguro#3]
Is this package still working? 
I am getting a 401 Unauthorized response.

And I am getting a 200 when using Postman with same credentials.

An example of how I am using it.
```php
$params = [
    'returnUrl' => 'https://www.example.com/return',
    'cancelUrl' => 'https://www.example.com/cancel',
    'amount' => '10.00',
];

$gateway->setEmail($email);
$gateway->setToken($token);
$gateway->setSandbox(true);

$gateway->send($params)->send();
```

**Comment by abdala** [comment]
I'm not sure, but I can't recognize this method `send`. What type of operation you are trying to do?

**Comment by jsgv** [comment]
My mistake it was supposed to be `$gateway->purchase($params)->send();`

I got it working by adding items to the purchase request object.

Redirect URL is not working, not sure if it's because of an outdated package or API issue.

**Comment by jsgv** [comment]
`purchase` is working as intended.

API options have to be enabled in sandbox account.
