### ISSUE TITLE
Refund support?

### ISSUE THREAD

**Issue by jsgv** [abdala/omnipay-pagseguro#4]
Any plan to add refund support?

**Comment by abdala** [comment]
No, no plans. But I can help you if you decide to add it.

Do you know how the collaboration process works? Fork, Pull Request, etc? If you don't, I can also help you with this :)

There is a good start here: https://help.github.com/en/categories/collaborating-with-issues-and-pull-requests

**Comment by jsgv** [comment]
Yes I know how to contribute :) 

I'm not super familiar with Omnipay packages, but I might create a PR if I have time to look into it.

**Comment by jsgv** [comment]
@abdala Created PR for refund support.
