### ISSUE TITLE
omnipay 3

### ISSUE THREAD

**Issue by lucassmacedo** [abdala/omnipay-pagseguro#7]
Ola! Este plugin está compatível com o omnipay 3?

**Comment by abdala** [comment]
Ola, Lucas! 

Ainda nao testei. Teve alguma modificacoes na API?

**Comment by abdala** [comment]
Olhei aqui:

https://github.com/thephpleague/omnipay-common/blob/master/UPGRADE.md

Mudaram algumas coisas, entao, ainda nao esta compativel.

Quer colaborar com esse upgrade?

**Comment by lucassmacedo** [comment]
Legal! Quero sim!

**Comment by jsgv** [comment]
I upgraded the package to omnipay 3.0 in my fork.
Would you like me to create a PR?

**Comment by abdala** [comment]
Sure!
